spring.application.name=jobportal
# Server
server.port=8080

# Database (MySQL)
spring.datasource.url=jdbc:mysql://localhost:3306/jobportal_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

jwt.secret=ThisIsASecretKeyForJwtPleaseMakeItLongEnough123

# Validation error format
server.error.include-message=always

cloudinary.cloud-name=dmqjdhq3x
cloudinary.api-key=162416566459794
cloudinary.api-secret=wIf_koXu1CmlAk5GCmgPwVH2ZmM

# Email (Gmail SMTP)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=jayantparmar291@gmail.com
spring.mail.password=ewrrghcvzqkumwqs
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Swagger / OpenAPI
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html